version: "3.8"
services:
  cbtd--proxy:
    container_name: cbtd--proxy
    image: nginx
    restart: 'no'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl.key:/ssl.key
      - ./ssl.crt:/ssl.crt
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '443:443'
  cbtd--postgres:
    container_name: cbtd--postgres
    restart: 'no'
    image: mysql:8.1
    volumes:
      - cbtd--mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: cbtd-dev
      MYSQL_PASSWORD: cbtd-dev
      MYSQL_DATABASE: cbtd-dev
      MYSQL_ROOT_PASSWORD: cbtd-dev
volumes:
  cbtd--mysql:
